# Generated by Django 5.2.9 on 2026-01-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pedido_cliente_remove_pedido_mesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
    ]
