# Generated by Django 5.2.9 on 2026-01-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_detallepedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio_unitario',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
