# Generated by Django 5.2.9 on 2026-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_fecha_pedido_creado_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='creado',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Preparando', 'Preparando'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
