# Generated by Django 5.2.9 on 2026-01-02 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pedido_cliente_remove_pedido_mesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido'),
        ),
    ]
