# Generated by Django 5.2.9 on 2026-01-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pedido_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
    ]
