# Generated by Django 5.2.9 on 2026-01-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_detallepedido_pedido_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallePedido',
            new_name='ItemPedido',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
