# Generated by Django 5.2.9 on 2026-01-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
