# Generated by Django 5.2.9 on 2026-01-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_detallepedido_itempedido_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPedido',
            new_name='PedidoProducto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
