# Generated by Django 5.2.9 on 2026-01-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_itempedido_pedidoproducto_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='creado',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En preparación'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
